### ISSUE TITLE
Alte Branches löschen

### ISSUE THREAD

**Issue by WGPSenshi** [OperationPandoraTrigger/OPT-Mod#11]
Gibt noch zwei alte Branches von pmayd, die wir glaube ich nicht brauchen. Denke, das Main-Repo sollte eh so schlank wie möglich bleiben. Idealerweise nur ein Dev-Branch und ggf. Release-Branches als Archivfunktion (je nachdem wie wir uns da entscheiden, Tags etc.).

Verwirrt Git-Neulinge und müllt Forks zu.

**Comment by Krzmbrzl** [comment]
Hab ich grad gemacht xDD

Es wird aber auch noch einen `tools` branch geben, sodass tool-updates immer eingepflegt werden können, ohne irgendwelche Code-Änderungen mitzuschleppen ;)
