### ISSUE TITLE
[Diskussion] Deutsch oder Englisch

### ISSUE THREAD

**Issue by Krzmbrzl** [OperationPandoraTrigger/OPT-Mod#2]
Wir sollten uns hier mal direkt am Anfang überlegen, ob wir das Repo auf Deutsch oder Englisch halten wollen und das dan einheitlich machen.

Und damit beziehe ich mich jetzt nicht auf Kommentare in irgendwelchen Hilfsskripts, die ohnehin kaum jemand lesen wird, sondern die Einträge im WIki, die Issues (plus Templates), Readme usw.

Ich hab das alles mal auf Deutsch angefangen, da es ja im Team Leute gibt, die Englisch nicht beherrschen, aber @pmayd hat zB. die Issue-Templates auf Englisch gemacht.
Meiner Meinung nach sollte das aber einheitlich sein.

**Comment by Krzmbrzl** [comment]
Meine Meinung: Ich präferiere Englisch, aber da das nicht von allen verstanden wird, hab ih auch kein Problem damit das ganze auf Deutsch zu machen.

**Comment by pmayd** [comment]
Weil die Templates in Englisch vorgeschrieben waren. Bezweifel, dass die jemand überhaupt nutzt aber das ist momentan nicht das Hauptproblem und kann man jederzeit umstellen. Es sind ja noch nicht mal alle hier Mitglied....

Ich präferiere auch Englisch, aber es werden nunmal nicht alle Englisch kommentieren etc. Man kann aber ohne Probleme ja jemanden bestimmen, der die Issues anlegt. Das müssen ja nicht alle können. Aber wahrscheinlich ist es am einfachsten, die Erklärungen auf Englisch zu halten, wie jeder seinen Code kommentiert ist ja egal. Nur hat man dann Probleme, dass alle Quellen etc. auf Englisch sind und man ggf. englischen Text als Zitat dann einfügt oder übersetzen muss....Aber diejenigen, die kein Englisch können, schreiben ja auch nicht die ganzen Dokus...aber es ist jetzt auch kein Open Source Project, dass viele Leute forken werden und es ist auch nicht als öffentliche API gedacht, von daaher spricht nichts gegen Deutsch

**Comment by pmayd** [comment]
Würde gerne einfach die Entscheidung für Englisch treffen, aber das ist eher aus selbstsüchtigen/gewohnheitsmäßigen Gründen und weil ich natürlich mit der Sprache keine Probleme habe, aber es wäre wohl nicht wirklich inklusiv für alle

**Comment by Krzmbrzl** [comment]
Ja so seh ich das auch. Aber was ich eben auf jeden Fall vermeiden will, ist eine Vermischung. Weil dann isses komisch wenn ich mir jedes Mal überlegen muss, in welchem Kontext ich jetzt welche Sprache verwenden soll...

**Comment by pmayd** [comment]
Ja gar keine Frage, daher wird es Deutsch sein

**Comment by Krzmbrzl** [comment]
Gut - Damit wäre das Issue auch erledigt ^^

**Comment by Krzmbrzl** [comment]
@GNCLORD-MDB 
Der Funktionsheader (https://opt4.net/forum/index.php?thread/2045-template-funktions-header/&postID=53590#post53590) passt nicht zu dem Konsens hier...

**Comment by GNCLORD-MDB** [comment]
Oh ja Toll ,hat ja keiner geschrieben das wir uns auf Deutsch geeinigt haben. 
Ich erstellt dann einen Deutschen Header

**Comment by Krzmbrzl** [comment]
Öhm was hier auf GitHub in den Issues geschrieben wird, solltest du dir schon auch mit durchlesen.
Wenn du daovn nichts mit bekommen hast, dann klick einfach oben auf den `watch` button, um in Zukunft über sowas benachrichtgit zu werden.

**Comment by GNCLORD-MDB** [comment]
elementare Dinge soll nicht hier sonder im Forum gemacht werden, die gehen hier unter sonst vielleicht.
Alles was rein mit den Modul zu tunen hat soll hier sein.

**Comment by Krzmbrzl** [comment]
Aber das hat rein mit den Modulen zu tun. Die Entwicklung läuft nunmal über GitHub. Dementsprechend müssen alle Entwickler auch mal hier vorbei schauen oder besser: Das Repo auf watch setzen
