### ISSUE TITLE
Fehlermeldung mit neuen Bauscript 

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Mod#24]
ich habe eine Fehlermeldung mit den neuen Scripten 

https://s17.directupload.net/images/190601/vc7oi555.jpg

Falscher Brunch

**Comment by GNCLORD-MDB** [comment]
Ich habe den Fehler noch, woher kommt der ?

**Comment by Krzmbrzl** [comment]
Wenn du die Nachricht eingehender studieren würdest, würde dir auffallen, dass da sein Fehler, ondern eine Warnung ist. Die ist nicht weiter schlimm

**Comment by Frozen-byte** [comment]
das ist kein Fehler da vor steht "warning" in Farbig.

Die Meldung kommt da die Versionsnummer ein String ist, der nicht korrekt mit Anführungsstrichen umgeben wurde.
