### ISSUE TITLE
[Diskussion] MakePBO vs. armake

### ISSUE THREAD

**Issue by Krzmbrzl** [OperationPandoraTrigger/OPT-Mod#3]
Wir sollten uns vllt auch mla darüber unterhalten, welche tools wir für die Mod verwenden bzw vielmehr unterstützen wollen.

Ich denke da haben wir im Wesentlichen Mikeros `makepbo` und `armake2` als Option.

Gleich vornweg: Ideal wäre, wenn wir es so hin bekommen, dass das Projekt mit beiden tools gebaut werden kann und die gleiche PBO entsteht (also gleicher Name + gleicher Inhalt).

Auch vorweg: Ich hab noch nie mit makepbo gearbeitet, dh. was ich gleich schreibe ist ggf. falsch. in diesem Fall bitte einfach korrigieren :)

| makepbo | armake2 |
| ------------ | ----------- |
| Schon sehr lange im Einsatz | Aktuell noch in der Entwicklung (PBO packen ist aber eigentlich fertig) |
| ~~Windows only (Könnte ein Problem sein, wenn man automatische Synchro zwischen Server und GitHub haben will, da dann ggf. der Server die PBO bauen können sollte)~~ | Cross-plattform |
| ~~Benötigt Einrichten einer "P-Drive"~~ | Kann ohne weitere Konfiguration verwendet werden |
| Closed Source | Open Source |

Ich denke das Einrichten, dass beide Tools verwendet werden können, sollte gut machbar sein, aber man kann dann eben nur features verwenden, die auch beide Tools unterstützen. Als Beispiel fällt mir da ein, dass die PBO-Benennung in `makepbo` wohl über eine Datei `pboName.h` funktioniert, während das meines Wissens nach mit `armake2` nicht geht. Dementsprechend wäre das etwas, was man nicht verwenden könnte/sollte (wenn uns das wirklich stört, könnte man dieses Feature aber auch in armake nachrüsten, da es ja OpenSource ist).

**Comment by pmayd** [comment]
Linux ist verfügbar, meinte @Frozen-byte

**Comment by Krzmbrzl** [comment]
Also auf der Download-Seite find ich `depbo-tools-0.6.88-linux-64bit.tgz`. Weiß nicht ob da alle für uns benötigten Tools dabei sind, aber wenn Frozen-byte das sagt, dann glaub ich das gern :D

> Auch brauchst du kein P-Drive.

Interessant - Und ich hatte in Erinnerung, dass die ursprüngliche Motivation hinter armake war, dass man die P-Drive im Gegensatz zu diesen Tools nicht braucht xD

> makepbo braucht die pboName.h NICHT, sie wird nur unterstützt. Du kannst optional bei makePBO einfach einen output-Namen eingeben, also auch manuell die Versionsnummer übergeben

Ich wollte auch eher darauf raus, dass man dieses Feature dann nicht nutzen sollte, da es nicht von beiden Tools unterstützt wird.

**Comment by pmayd** [comment]
klar, natürlich, wenn dass der Fall ist. Grundsätzlich haben wir ja erstmal mit dem Build-Tool auch nichts direkt zu tun, da dass die Entscheidung des Serverteams ist und wenn die uns sagen, unterstützt bitte beide Tools, dann passen wir das an, aber ansonsten könnt ihr das einfach vorgeben, ich will nur eine automatische PBO und einen automatischen Serverneustart :p

**Comment by pmayd** [comment]
bzgl P:Drive bin ja kein Modder aber das kann schon sein, wenn es vielleicht um Abhängigkeiten geht? makePBO kann ja unglaublich viel überprüfen und wenn er Pfade aus der config.cpp oder sonstwo prüft, dann weiß ich nicht was passiert, wenn man zum Beispiel BI Texturen etc. verlinkt. Also für das, was ich bisher damit mache, brauche ich nichts einrichten, aber vielleicht muss man das, wenn man BI-Inhalte verändern will etc. Aber dann muss man das ja aus anderen Gründen eh

**Comment by Krzmbrzl** [comment]
Da ich mich nur mit armake auskenne, würde ich den Support (wie ich es mit meinen Skripten aj schon angefangen hab) dafür erledigen. Wenn dann noch jemand die Skripte liefert/anpasst, dass auch makePBO unterstützt wird, dann gerne :)

**Comment by Frozen-byte** [comment]
ich habe mit makePBO angefangen, da ich keine Binaries von armake2 gefunden habe. Ansonsten würde ich mir das auch Mal anschauen.

Generell bin ich immer für OpenSource, jedoch glaube ich dass es in unserem Kontext wirklich keine Rolle spielt (bei einem Proprietären Spiel)

Daher ist es mir Persönlich egal, wenn sie beide gefühlt gleich schnell kompilieren.
